version: '3'
services:
  api-server:
    restart: unless-stopped
    build: .
    ports: 
      - 5000:5000
    networks:
      - nw

  mongo:
    image: mongo:latest
    volumes: 
      - mongodb:/data/db
    networks:
      - nw

networks:
  nw:
    driver: bridge

volumes:
  mongodb:

